tap "homebrew/bundle"
tap "homebrew/core"
tap "sanemat/font"
brew "ghq"
brew "git"
brew "goenv", args: ["HEAD"]
brew "mysql"
brew "node"
brew "nvm"
brew "peco"
brew "pipenv"
brew "poetry"
brew "pyenv"
brew "rbenv"
brew "yarn"
brew "sanemat/font/ricty"
